### ISSUE TITLE
Print version number in standard out.

### ISSUE THREAD

**Issue by rwblair** [bids-standard/legacy-validator#770] opened 2019-04-17 20:08 UTC
Would be useful in situation where bids-validator is being embedded in reports:
https://github.com/poldracklab/fmriprep/pull/1583

**Comment by sappelhoff** [comment] 2019-05-07 08:00
possible duplicate of https://github.com/bids-standard/bids-validator/issues/602

**Closed as completed** 2019-07-12 16:37 UTC
