### ISSUE TITLE
deno validator: complains about EVENT_ONSET_ORDER but AFAIK they are sorted!

### ISSUE THREAD

**Issue by yarikoptic** [bids-standard/legacy-validator#2006] opened 2024-06-21 00:35 UTC
Got
```
        [WARNING] The onset column in events.tsv files should be sorted.
 (EVENT_ONSET_ORDER)

                ./sub-0001/ses-02/func/sub-0001_ses-02_task-narratives_acq-mb8_run-01_events.tsv
                        Evidence: schema.rules.rules.checks.events.SortedOnsets
...
                ./sub-0131/ses-04/func/sub-0131_ses-04_task-social_acq-mb8_run-02_events.tsv
                        Evidence: schema.rules.rules.checks.events.SortedOnsets
...
                ./sub-0147/ses-04/func/sub-0147_ses-04_task-fractional_acq-mb8_run-01_desc-posner_events.tsv
                        Evidence: schema.rules.rules.checks.events.SortedOnsets

        Please visit https://neurostars.org/search?q=EVENT_ONSET_ORDER for existing conversations about this issue.
```

but if I look into those files -- look sorted to me:

```shell
(deno) yoh@typhon:/mnt/DATA/data/yoh/1076_spacetop$ diff -Naur ./sub-0131/ses-04/func/sub-0131_ses-04_task-social_acq-mb8_run-02_events.tsv <(sort -n < ./sub-0131/ses-04/func/sub-0131_ses-04_task-social_acq-mb8_run-02_events.tsv)
(deno) yoh@typhon:/mnt/DATA/data/yoh/1076_spacetop$ 
```

full file is http://www.oneukrainian.com/tmp/sub-0131_ses-04_task-social_acq-mb8_run-02_events.tsv (we are yet to upload to openneuro)

**Comment by rwblair** [comment] 2024-08-07 22:27
I believe this was fixed in #2022. Am unable to reproduce on master, closing for now on provided tsv file.

**Closed as completed by rwblair** 2024-08-07 22:27 UTC
Labels: schema
