### ISSUE TITLE
Command-line option to ignore data contents

### ISSUE THREAD

**Issue by Lestropie** [bids-standard/legacy-validator#2074] opened 2024-08-12 03:06 UTC
I am currently attempting to execute the validator, with a proposed update to the scheme, on a proposed example dataset:
https://github.com/bids-standard/bids-specification/pull/1864
https://github.com/bids-standard/bids-examples/pull/452

I see that command-line option `--ignoreNiftiHeaders` is available, which suppresses a subset of errors produced when running on these data. However another error appears reporting that empty files are not permitted.

I wonder if the *intent* of the existing `--ignoreNiftiHeaders` option is to facilitate execution of the validator against data-stripped datasets, but it is no longer exhaustive in such and therefore no longer achieves its purported aim. What would be better is a command-line option along the lines of "disable data checks"; ie. validate the filesystem path, and associated metadata, but bypass *all* checks of data file contents (image header, file size, anything else)?

**Comment by effigies** [comment] 2024-08-12 14:14
Duplicate of https://github.com/bids-standard/bids-validator/issues/1937.

**Closed as not planned by effigies** 2024-08-12 14:14 UTC
