### ISSUE TITLE
How can we validate this derivaties rule regarding the use of _desc-<label>?

### ISSUE THREAD

**Issue by rwblair** [bids-standard/legacy-validator#984] opened 2020-06-23 23:04 UTC
When necessary to distinguish two files that do not otherwise have a distinguishing entity, the _desc-<label> keyword-value SHOULD be used. This includes the cases of needing to distinguish both differing inputs and differing outputs (for example, _desc-T1w and _desc-T2w to distinguish brain mask files derived from T1w and T2w images; or _desc-sm4 and _desc-sm8 to distinguish between outputs generated with two different levels of smoothing).

Don't think the validator can know whether or not files should be using _desc. And if _desc is being used we can just double check that the its a valid label.

**Comment by effigies** [comment] 2020-11-10 02:24
I think this is basically a duplicate of #980. The idea here was to say "You have to have some non-raw entity. In the last resort, you can always use desc."

**Comment by soichih** [comment] 2021-02-11 21:29
I am having a problem passing bids-validator with dataset with -desc.. like this.

```
└── sub-9002
    └── ses-1
        ├── anat
        │   ├── sub-9002_ses-1_desc-4_T2w.json
        │   ├── sub-9002_ses-1_desc-4_T2w.nii.gz
        │   ├── sub-9002_ses-1_T1w.json
        │   └── sub-9002_ses-1_T1w.nii.gz
        ├── fmap
        │   ├── sub-9002_ses-1_desc-5_magnitude1.nii.gz
        │   ├── sub-9002_ses-1_desc-5_magnitude2.nii.gz
        │   ├── sub-9002_ses-1_desc-5_phase1.json
        │   ├── sub-9002_ses-1_desc-5_phase1.nii.gz
        │   ├── sub-9002_ses-1_desc-5_phase2.json
        │   └── sub-9002_ses-1_desc-5_phase2.nii.gz
        └── func
            ├── sub-9002_ses-1_task-rest_desc-2_bold.json
            └── sub-9002_ses-1_task-rest_desc-2_bold.nii.gz
```

Am I not supposed to be using `desc-` for raw input? (it's only for derivatives?)

```
╰─$ bids-validator .            
bids-validator@1.5.8

	1: [ERR] Files with such naming scheme are not part of BIDS specification. This error is most commonly caused by typos in file names that make them not BIDS compatible. Please consult the specification and make sure your files are named correctly. If this is not a file naming issue (for example when including files not yet covered by the BIDS specification) you should include a ".bidsignore" file in your dataset (see https://github.com/bids-standard/bids-validator#bidsignore for details). Please note that derived (processed) data should be placed in /derivatives folder and source data (such as DICOMS or behavioural logs in proprietary formats) should be placed in the /sourcedata folder. (code: 1 - NOT_INCLUDED)
		./sub-9002/ses-1/anat/sub-9002_ses-1_desc-4_T2w.json
			Evidence: sub-9002_ses-1_desc-4_T2w.json
		./sub-9002/ses-1/anat/sub-9002_ses-1_desc-4_T2w.nii.gz
			Evidence: sub-9002_ses-1_desc-4_T2w.nii.gz
		./sub-9002/ses-1/fmap/sub-9002_ses-1_desc-5_magnitude1.nii.gz
			Evidence: sub-9002_ses-1_desc-5_magnitude1.nii.gz
		./sub-9002/ses-1/fmap/sub-9002_ses-1_desc-5_magnitude2.nii.gz
			Evidence: sub-9002_ses-1_desc-5_magnitude2.nii.gz
		./sub-9002/ses-1/fmap/sub-9002_ses-1_desc-5_phase1.json
			Evidence: sub-9002_ses-1_desc-5_phase1.json
		./sub-9002/ses-1/fmap/sub-9002_ses-1_desc-5_phase1.nii.gz
			Evidence: sub-9002_ses-1_desc-5_phase1.nii.gz
		./sub-9002/ses-1/fmap/sub-9002_ses-1_desc-5_phase2.json
			Evidence: sub-9002_ses-1_desc-5_phase2.json
		./sub-9002/ses-1/fmap/sub-9002_ses-1_desc-5_phase2.nii.gz
			Evidence: sub-9002_ses-1_desc-5_phase2.nii.gz
		./sub-9002/ses-1/func/sub-9002_ses-1_task-rest_desc-2_bold.json
			Evidence: sub-9002_ses-1_task-rest_desc-2_bold.json
		./sub-9002/ses-1/func/sub-9002_ses-1_task-rest_desc-2_bold.nii.gz
			Evidence: sub-9002_ses-1_task-rest_desc-2_bold.nii.gz
```

If desc- is only for derivatives, what should I do to make sure that 2 objects with the same entities won't overwrite each other?

**Comment by effigies** [comment] 2021-02-11 21:31
`desc-` is just for derivatives. What's the use case for `desc-` in raw? It may be better served by another entity.

**Comment by soichih** [comment] 2021-02-11 21:34
humm.. ok. I was thinking something like multiple dwi with different PED.. but I guess I should set dir- entity in that case.

**Closed as completed** 2024-11-05 16:47 UTC
Labels: enhancement, derivatives
